import {
  Activity, Globe2, Search, BarChart3, Bell, ScrollText, Shield, Lock, Smartphone,
  LineChart, Store, Package, CreditCard, Wallet, KeyRound, Users2, Building2,
  PenLine, Handshake, Megaphone, Layers3, Boxes, FileText, UserCircle, ShoppingCart,
  Target, TrendingUp, LifeBuoy, MessageSquare, HeartPulse, Rocket, MessagesSquare,
  Mail, Phone, BookOpen, BrainCircuit, Plug, Wand2, Bot, Cpu, Workflow, Terminal,
  Server, Mic2, HelpCircle, Hammer, Zap, Eye, Logs, BugPlay, AppWindow, Smartphone as Apk,
  PlayCircle, GitBranch, GitMerge, CloudUpload, Network, Database, FolderTree, PieChart,
  HardDrive, Cloud, Globe, Gauge, ListTree, Webhook, Archive, ShieldAlert, MapPinned,
  MonitorSmartphone, Briefcase, BadgeDollarSign, Truck, Factory, KanbanSquare, ClipboardList,
  NotebookText, UserSquare, Coins, Settings, Scale, Gavel, Building, Plug2, Radio, Radar,
  Router as RouterIcon, Palette, LayoutDashboard, FileBarChart, GaugeCircle, Headset,
  SearchCheck, UserCog, Star, Code2, Library,
  // HR / People Hub
  CalendarCheck, CalendarDays, FileBadge, Award, UserPlus, Files,
  // Campaign Compass
  Vote, MapPin, Users, Megaphone as Bullhorn, Video, Car, Sparkles, MessageCircle,
  Newspaper, BadgeCheck, Crosshair, Camera, Truck as VanIcon, ClipboardCheck,
  Flag, Trophy, Banknote, BarChart, Tv2, MapPinned as GeoIcon, Map, Component,
  Layers, Workflow as FlowIcon, BookMarked, FileSpreadsheet, Compass, Wallet as Money,
  Building2 as College, GraduationCap, ShieldCheck, Boxes as Stack, ChartBar,
  // Creator Hub (LMS) + Payroll
  PlaySquare, BookOpenCheck, Presentation, NotepadText, PencilRuler, Receipt,
  Calculator, PiggyBank, Landmark, FileCheck2, ScrollText as Pay, TrendingDown,
  // MLM + POS
  GitFork, Gift, Trophy as RankIcon, RefreshCw, Printer, ScanLine, Tags,
  Percent, Crown, Banknote as Cash, Building2 as Company,
  // Data Vala + Dezortn
  DatabaseZap, Download, Heart, ShoppingBag, Filter, Sparkle, Send,
  TrendingUp as Growth, BarChart2, UserPlus2,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type NavItem = {
  id: number;
  title: string;
  clone: string;
  path: string;
  icon: LucideIcon;
  built?: boolean;
};

export type NavGroup = {
  label: string;
  items: NavItem[];
};

export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Command",
    items: [
      { id: 1, title: "Boss Panel", clone: "Palantir + Datadog", path: "/", icon: LayoutDashboard, built: true },
      { id: 2, title: "Executive War Room", clone: "Palantir Gotham", path: "/war-room", icon: Globe2, built: true },
      { id: 3, title: "Global Search", clone: "Raycast", path: "/search", icon: Search, built: true },
      { id: 80, title: "Global Settings", clone: "Windows Admin Center", path: "/settings", icon: Settings },
      { id: 87, title: "Centralized Router", clone: "Next.js App Router", path: "/router", icon: RouterIcon },
    ],
  },
  {
    label: "Observability",
    items: [
      { id: 4, title: "Analytics Manager", clone: "Power BI + Tableau", path: "/analytics", icon: BarChart3, built: true },
      { id: 5, title: "Notification Manager", clone: "PagerDuty", path: "/notifications", icon: Bell },
      { id: 6, title: "Audit Logs", clone: "Splunk", path: "/audit", icon: ScrollText },
      { id: 10, title: "Monitoring System", clone: "Datadog", path: "/monitoring", icon: Activity, built: true },
      { id: 49, title: "Realtime Logs", clone: "Kibana", path: "/logs", icon: Logs },
      { id: 50, title: "Crash Monitoring", clone: "Sentry", path: "/crashes", icon: BugPlay },
      { id: 60, title: "App Analytics", clone: "Firebase Analytics", path: "/app-analytics", icon: PieChart },
      { id: 69, title: "Geo Monitoring", clone: "Azure Maps", path: "/geo", icon: MapPinned },
      { id: 90, title: "Enterprise Reporting", clone: "Crystal Reports", path: "/reporting", icon: FileBarChart },
      { id: 91, title: "Monitoring Core", clone: "New Relic", path: "/monitoring-core", icon: GaugeCircle },
    ],
  },
  {
    label: "Security & Identity",
    items: [
      { id: 7, title: "Security Manager", clone: "Cloudflare Zero Trust", path: "/security", icon: Shield, built: true },
      { id: 8, title: "Auth / RBAC", clone: "Auth0 + Clerk", path: "/auth", icon: Lock },
      { id: 9, title: "Session / Devices", clone: "Microsoft Intune", path: "/devices", icon: Smartphone },
      { id: 68, title: "Fraud / Risk", clone: "Darktrace", path: "/fraud", icon: ShieldAlert },
      { id: 70, title: "Remote Access", clone: "TeamViewer Tensor", path: "/remote", icon: MonitorSmartphone },
      { id: 83, title: "Multi-Tenant Engine", clone: "Clerk Orgs", path: "/tenants", icon: Building },
    ],
  },
  {
    label: "Commerce",
    items: [
      { id: 11, title: "Marketplace", clone: "CodeCanyon", path: "/marketplace", icon: Store, built: true },
      { id: 12, title: "Product Manager", clone: "Shopify Admin", path: "/products", icon: Package },
      { id: 13, title: "Subscriptions", clone: "Stripe Billing", path: "/billing", icon: CreditCard },
      { id: 14, title: "Payments", clone: "Stripe", path: "/payments", icon: Wallet },
      { id: 15, title: "License Manager", clone: "Gumroad License", path: "/licenses", icon: KeyRound },
      { id: 23, title: "Invoice / Books", clone: "Zoho Books", path: "/books", icon: FileText },
      { id: 25, title: "Order Management", clone: "Shopify Orders", path: "/orders", icon: ShoppingCart },
      { id: 79, title: "Finance System", clone: "NetSuite", path: "/finance", icon: Coins },
    ],
  },
  {
    label: "Partners",
    items: [
      { id: 16, title: "Reseller System", clone: "PartnerStack", path: "/resellers", icon: Handshake },
      { id: 17, title: "Franchise", clone: "GoHighLevel", path: "/franchise", icon: Building2 },
      { id: 18, title: "Author System", clone: "Gumroad Creator", path: "/authors", icon: PenLine },
      { id: 19, title: "Affiliate", clone: "Impact", path: "/affiliates", icon: Megaphone },
      { id: 20, title: "Influencer", clone: "Upfluence", path: "/influencers", icon: Star },
      { id: 21, title: "White Label", clone: "GoHighLevel", path: "/white-label", icon: Layers3 },
      { id: 22, title: "SaaS Tenants", clone: "Shopify Partners", path: "/saas", icon: Boxes },
    ],
  },
  {
    label: "Customer",
    items: [
      { id: 24, title: "Customer Mgmt", clone: "Salesforce", path: "/customers", icon: UserCircle },
      { id: 26, title: "CRM & Leads", clone: "Salesforce CRM", path: "/crm", icon: Target, built: true },
      { id: 27, title: "Sales", clone: "HubSpot", path: "/sales", icon: TrendingUp },
      { id: 28, title: "Support", clone: "Zendesk", path: "/support", icon: LifeBuoy },
      { id: 29, title: "Ticket + Chat AI", clone: "Freshdesk", path: "/tickets", icon: MessageSquare },
      { id: 30, title: "Customer Success", clone: "Gainsight", path: "/success", icon: HeartPulse },
      { id: 31, title: "Onboarding", clone: "Appcues", path: "/onboarding", icon: Rocket },
    ],
  },
  {
    label: "Communications",
    items: [
      { id: 32, title: "Comms Hub", clone: "Slack", path: "/comms", icon: MessagesSquare },
      { id: 33, title: "Email System", clone: "Mailchimp", path: "/email", icon: Mail },
      { id: 34, title: "WhatsApp / SMS", clone: "Twilio", path: "/sms", icon: Phone },
      { id: 35, title: "Knowledge Base", clone: "Intercom", path: "/knowledge", icon: BookOpen },
    ],
  },
  {
    label: "AI",
    items: [
      { id: 36, title: "Vala AI", clone: "OpenAI Enterprise", path: "/ai", icon: BrainCircuit, built: true },
      { id: 37, title: "AI API Manager", clone: "OpenRouter", path: "/ai/api", icon: Plug },
      { id: 38, title: "AI Builder", clone: "Retool AI", path: "/ai/builder", icon: Wand2 },
      { id: 39, title: "AI Bot Market", clone: "GPT Store", path: "/ai/bots", icon: Bot },
      { id: 40, title: "AI Agents", clone: "AutoGPT", path: "/ai/agents", icon: Cpu },
      { id: 41, title: "AI Workflows", clone: "n8n", path: "/ai/workflows", icon: Workflow },
      { id: 42, title: "Prompt Manager", clone: "OpenWebUI", path: "/ai/prompts", icon: Terminal },
      { id: 43, title: "Model Manager", clone: "Ollama", path: "/ai/models", icon: Server },
      { id: 44, title: "Voice Assistant", clone: "ElevenLabs", path: "/ai/voice", icon: Mic2 },
      { id: 45, title: "Support Assistant", clone: "Intercom AI", path: "/ai/support", icon: HelpCircle },
    ],
  },
  {
    label: "Builder & DevOps",
    items: [
      { id: 46, title: "Tool Builder", clone: "Retool", path: "/builder", icon: Hammer },
      { id: 47, title: "Automation", clone: "Zapier", path: "/automation", icon: Zap },
      { id: 48, title: "Demo System", clone: "Vercel Preview", path: "/demos", icon: Eye },
      { id: 51, title: "App Builder", clone: "Bubble + Lovable", path: "/app-builder", icon: AppWindow },
      { id: 52, title: "APK Installer", clone: "Firebase Dist", path: "/apk", icon: Apk },
      { id: 53, title: "Play Console", clone: "Google Play", path: "/play", icon: PlayCircle },
      { id: 54, title: "Git Mgmt", clone: "GitHub", path: "/git", icon: GitBranch },
      { id: 55, title: "CI/CD", clone: "GitLab CI", path: "/ci", icon: GitMerge },
      { id: 56, title: "Deployments", clone: "Vercel", path: "/deploy", icon: CloudUpload },
      { id: 57, title: "API Gateway", clone: "Postman", path: "/api", icon: Network },
      { id: 58, title: "Database", clone: "Supabase Studio", path: "/db", icon: Database },
      { id: 59, title: "File Storage", clone: "Google Drive", path: "/files", icon: FolderTree },
    ],
  },
  {
    label: "Infrastructure",
    items: [
      { id: 61, title: "Server Manager", clone: "DigitalOcean", path: "/servers", icon: HardDrive, built: true },
      { id: 62, title: "Cloud Infra", clone: "AWS Console", path: "/cloud", icon: Cloud },
      { id: 63, title: "Domain / DNS", clone: "Cloudflare", path: "/dns", icon: Globe },
      { id: 64, title: "CDN / Cache", clone: "Cloudflare CDN", path: "/cdn", icon: Gauge },
      { id: 65, title: "Queue / Events", clone: "Kafka", path: "/queue", icon: ListTree },
      { id: 66, title: "Webhooks", clone: "Svix", path: "/webhooks", icon: Webhook },
      { id: 67, title: "Backup", clone: "Veeam", path: "/backup", icon: Archive },
      { id: 84, title: "Enterprise API", clone: "MuleSoft", path: "/enterprise-api", icon: Plug2 },
      { id: 85, title: "Event Bus", clone: "RabbitMQ", path: "/event-bus", icon: Radio },
      { id: 86, title: "Realtime Engine", clone: "Pusher", path: "/realtime", icon: Radar },
    ],
  },
  {
    label: "Operations",
    items: [
      { id: 71, title: "HR / Employees", clone: "Workday", path: "/hr-workday", icon: Users2 },
      { id: 72, title: "Payroll", clone: "ADP", path: "/payroll/dashboard", icon: BadgeDollarSign },
      { id: 73, title: "Assets", clone: "SAP Asset", path: "/assets", icon: Briefcase },
      { id: 74, title: "Vendors", clone: "SAP Ariba", path: "/vendors", icon: Truck },
      { id: 75, title: "Tasks", clone: "Jira + ClickUp", path: "/tasks", icon: KanbanSquare },
      { id: 76, title: "Projects", clone: "Monday.com", path: "/projects", icon: ClipboardList },
      { id: 77, title: "Documents", clone: "Notion", path: "/docs", icon: NotebookText },
      { id: 78, title: "Client Panel", clone: "WHMCS", path: "/clients", icon: UserSquare },
    ],
  },
  {
    label: "Legal & Design",
    items: [
      { id: 81, title: "Law & Order", clone: "Gov Case Control", path: "/law", icon: Scale },
      { id: 82, title: "Lawyer Dashboard", clone: "Legal Tracker", path: "/lawyer", icon: Gavel },
      { id: 101, title: "Legal Pro", clone: "Thomson Reuters", path: "/lawyer-pro", icon: Library },
      { id: 88, title: "Design System", clone: "Figma Enterprise", path: "/design-system", icon: Palette },
      { id: 89, title: "Dashboard Engine", clone: "Retool Dash", path: "/dash-engine", icon: Factory },
    ],
  },
  {
    label: "Portals",
    items: [
      { id: 92, title: "Support Team", clone: "Freshdesk Agent", path: "/portal/support", icon: Headset },
      { id: 93, title: "SEO Workspace", clone: "Semrush", path: "/portal/seo", icon: SearchCheck },
      { id: 94, title: "User Portal", clone: "Stripe Portal", path: "/portal/user", icon: UserCog },
      { id: 95, title: "Author Portal", clone: "Gumroad", path: "/portal/author", icon: PenLine },
      { id: 96, title: "Reseller Portal", clone: "PartnerStack", path: "/portal/reseller", icon: Handshake },
      { id: 97, title: "Franchise Portal", clone: "GoHighLevel", path: "/portal/franchise", icon: Building2 },
      { id: 98, title: "Affiliate Portal", clone: "Impact", path: "/portal/affiliate", icon: Megaphone },
      { id: 99, title: "Influencer Portal", clone: "Upfluence", path: "/portal/influencer", icon: Star },
      { id: 100, title: "Developer Portal", clone: "GitHub", path: "/portal/dev", icon: Code2 },
    ],
  },
  {
    label: "HR · People Hub",
    items: [
      { id: 200, title: "HR Dashboard", clone: "People Hub", path: "/hr/dashboard", icon: LayoutDashboard, built: true },
      { id: 201, title: "Employees", clone: "People Hub", path: "/hr/employees", icon: Users2 },
      { id: 202, title: "Attendance", clone: "People Hub", path: "/hr/attendance", icon: CalendarCheck },
      { id: 203, title: "Leave Management", clone: "People Hub", path: "/hr/leave", icon: CalendarDays },
      { id: 204, title: "Performance", clone: "People Hub", path: "/hr/performance", icon: Award },
      { id: 205, title: "Documents", clone: "People Hub", path: "/hr/documents", icon: Files },
      { id: 206, title: "Shared Documents", clone: "People Hub", path: "/hr/documents-shared", icon: FileBadge },
      { id: 207, title: "Company", clone: "People Hub", path: "/hr/company", icon: Building2 },
      { id: 208, title: "HR Admin", clone: "People Hub", path: "/hr/admin", icon: UserCog },
      { id: 209, title: "HR Settings", clone: "People Hub", path: "/hr/settings", icon: Settings },
      { id: 210, title: "HR Auth", clone: "People Hub", path: "/hr/auth", icon: Lock },
    ],
  },
  {
    label: "Campaign · Compass",
    items: [
      { id: 300, title: "Campaign Dashboard", clone: "Campaign Compass", path: "/campaign/dashboard", icon: LayoutDashboard, built: true },
      { id: 301, title: "Control Room", clone: "Campaign Compass", path: "/campaign/control-room", icon: Radar, built: true },
      { id: 302, title: "AI Prediction", clone: "Campaign Compass", path: "/campaign/ai-prediction", icon: BrainCircuit, built: true },
      { id: 303, title: "Election Intelligence", clone: "Campaign Compass", path: "/campaign/intelligence", icon: Crosshair },
      { id: 304, title: "Constituency", clone: "Campaign Compass", path: "/campaign/constituency", icon: Map },
      { id: 305, title: "Booths", clone: "Campaign Compass", path: "/campaign/booths", icon: Vote },
      { id: 306, title: "Booth Map", clone: "Campaign Compass", path: "/campaign/booth-map", icon: GeoIcon },
      { id: 307, title: "Voters", clone: "Campaign Compass", path: "/campaign/voters", icon: Users },
      { id: 308, title: "Voter Dashboard", clone: "Campaign Compass", path: "/campaign/voter-dashboard", icon: UserCircle },
      { id: 309, title: "Caste Analytics", clone: "Campaign Compass", path: "/campaign/caste-analytics", icon: ChartBar },
      { id: 310, title: "Area Status", clone: "Campaign Compass", path: "/campaign/area-status", icon: MapPin },
      { id: 311, title: "Door To Door", clone: "Campaign Compass", path: "/campaign/door-to-door", icon: ClipboardCheck },
      { id: 312, title: "Events", clone: "Campaign Compass", path: "/campaign/events", icon: CalendarDays },
      { id: 313, title: "Calendar", clone: "Campaign Compass", path: "/campaign/calendar", icon: CalendarCheck },
      { id: 314, title: "Messaging", clone: "Campaign Compass", path: "/campaign/messaging", icon: MessageCircle },
      { id: 315, title: "Social Media Setup", clone: "Campaign Compass", path: "/campaign/social", icon: Bullhorn },
      { id: 316, title: "Creative Center", clone: "Campaign Compass", path: "/campaign/creative", icon: Sparkles },
      { id: 317, title: "Media Dashboard", clone: "Campaign Compass", path: "/campaign/media", icon: Tv2 },
      { id: 318, title: "Cameraman App", clone: "Campaign Compass", path: "/campaign/cameraman", icon: Camera },
      { id: 319, title: "Driver App", clone: "Campaign Compass", path: "/campaign/driver", icon: VanIcon },
      { id: 320, title: "Volunteer App", clone: "Campaign Compass", path: "/campaign/volunteer", icon: UserPlus },
      { id: 321, title: "Manager App", clone: "Campaign Compass", path: "/campaign/manager", icon: UserCog },
      { id: 322, title: "PA App", clone: "Campaign Compass", path: "/campaign/pa", icon: Headset },
      { id: 323, title: "Candidate Setup", clone: "Campaign Compass", path: "/campaign/candidate-setup", icon: Flag },
      { id: 324, title: "Candidate Mobile", clone: "Campaign Compass", path: "/campaign/candidate-mobile", icon: Smartphone },
      { id: 325, title: "Candidate Results", clone: "Campaign Compass", path: "/campaign/candidate-results", icon: Trophy },
      { id: 326, title: "Leader Profile", clone: "Campaign Compass", path: "/campaign/leader", icon: BadgeCheck },
      { id: 327, title: "Poll Day", clone: "Campaign Compass", path: "/campaign/poll-day", icon: Vote },
      { id: 328, title: "Result Day", clone: "Campaign Compass", path: "/campaign/result-day", icon: Trophy },
      { id: 329, title: "Post Election", clone: "Campaign Compass", path: "/campaign/post-election", icon: Flag },
      { id: 330, title: "Election Results KR", clone: "Campaign Compass", path: "/campaign/results-kr", icon: BarChart },
      { id: 331, title: "College Election", clone: "Campaign Compass", path: "/campaign/college", icon: GraduationCap },
      { id: 332, title: "Finance", clone: "Campaign Compass", path: "/campaign/finance", icon: Money },
      { id: 333, title: "Donations", clone: "Campaign Compass", path: "/campaign/donations", icon: Banknote },
      { id: 334, title: "Transport Expense", clone: "Campaign Compass", path: "/campaign/transport", icon: Car },
      { id: 335, title: "Reports", clone: "Campaign Compass", path: "/campaign/reports", icon: FileSpreadsheet },
      { id: 336, title: "Analytics", clone: "Campaign Compass", path: "/campaign/analytics", icon: PieChart },
      { id: 337, title: "Unified Dashboard", clone: "Campaign Compass", path: "/campaign/unified", icon: LayoutDashboard },
      { id: 338, title: "Role Dashboard", clone: "Campaign Compass", path: "/campaign/role-dashboard", icon: UserSquare },
      { id: 339, title: "Role Select", clone: "Campaign Compass", path: "/campaign/role-select", icon: UserCog },
      { id: 340, title: "Account Setup", clone: "Campaign Compass", path: "/campaign/account", icon: UserPlus },
      { id: 341, title: "White Label", clone: "Campaign Compass", path: "/campaign/white-label", icon: Layers3 },
      { id: 342, title: "Master Flow", clone: "Campaign Compass", path: "/campaign/master-flow", icon: FlowIcon },
      { id: 343, title: "API Flow", clone: "Campaign Compass", path: "/campaign/api-flow", icon: Network },
      { id: 344, title: "Database ERD", clone: "Campaign Compass", path: "/campaign/erd", icon: Database },
      { id: 345, title: "Deployment Arch", clone: "Campaign Compass", path: "/campaign/deployment", icon: CloudUpload },
      { id: 346, title: "Tech Stack", clone: "Campaign Compass", path: "/campaign/tech-stack", icon: Stack },
      { id: 347, title: "Security Matrix", clone: "Campaign Compass", path: "/campaign/security-matrix", icon: ShieldCheck },
      { id: 348, title: "UI Wireframe", clone: "Campaign Compass", path: "/campaign/wireframe", icon: Component },
      { id: 349, title: "Figma Layout", clone: "Campaign Compass", path: "/campaign/figma", icon: Palette },
      { id: 350, title: "User Journey", clone: "Campaign Compass", path: "/campaign/journey", icon: Compass },
      { id: 351, title: "Investor Deck", clone: "Campaign Compass", path: "/campaign/deck", icon: Newspaper },
      { id: 352, title: "Hero Showcase", clone: "Campaign Compass", path: "/campaign/hero-showcase", icon: Sparkles },
      { id: 353, title: "Login Showcase", clone: "Campaign Compass", path: "/campaign/login-showcase", icon: Lock },
      { id: 354, title: "Control Room Showcase", clone: "Campaign Compass", path: "/campaign/control-showcase", icon: Tv2 },
      { id: 355, title: "Super Admin", clone: "Campaign Compass", path: "/campaign/super-admin", icon: ShieldAlert },
      { id: 356, title: "Admin", clone: "Campaign Compass", path: "/campaign/admin", icon: UserCog },
      { id: 357, title: "Settings", clone: "Campaign Compass", path: "/campaign/settings", icon: Settings },
      { id: 358, title: "Auth", clone: "Campaign Compass", path: "/campaign/auth", icon: Lock },
    ],
  },
  {
    label: "Creator · Hub (LMS)",
    items: [
      { id: 400, title: "Creator Dashboard", clone: "Creator Hub", path: "/creator/dashboard", icon: LayoutDashboard, built: true },
      { id: 401, title: "Courses", clone: "Creator Hub", path: "/creator/courses", icon: BookOpen },
      { id: 402, title: "Course Builder", clone: "Creator Hub", path: "/creator/course-builder", icon: PencilRuler },
      { id: 403, title: "Course Detail", clone: "Creator Hub", path: "/creator/course-detail", icon: BookOpenCheck },
      { id: 404, title: "Content Library", clone: "Creator Hub", path: "/creator/library", icon: Library },
      { id: 405, title: "Video Portal", clone: "Creator Hub", path: "/creator/video", icon: PlaySquare },
      { id: 406, title: "Workshops", clone: "Creator Hub", path: "/creator/workshops", icon: Presentation },
      { id: 407, title: "Students", clone: "Creator Hub", path: "/creator/students", icon: Users },
      { id: 408, title: "Student Profile", clone: "Creator Hub", path: "/creator/student-profile", icon: UserCircle },
      { id: 409, title: "Trainers", clone: "Creator Hub", path: "/creator/trainers", icon: UserCog },
      { id: 410, title: "Assignments", clone: "Creator Hub", path: "/creator/assignments", icon: NotepadText },
      { id: 411, title: "Exams", clone: "Creator Hub", path: "/creator/exams", icon: ClipboardCheck },
      { id: 412, title: "Certificates", clone: "Creator Hub", path: "/creator/certificates", icon: Award },
      { id: 413, title: "Attendance", clone: "Creator Hub", path: "/creator/attendance", icon: CalendarCheck },
      { id: 414, title: "Forum", clone: "Creator Hub", path: "/creator/forum", icon: MessagesSquare },
      { id: 415, title: "Notifications", clone: "Creator Hub", path: "/creator/notifications", icon: Bell },
      { id: 416, title: "Fees", clone: "Creator Hub", path: "/creator/fees", icon: Receipt },
      { id: 417, title: "Payments", clone: "Creator Hub", path: "/creator/payments", icon: CreditCard },
      { id: 418, title: "Analytics", clone: "Creator Hub", path: "/creator/analytics", icon: PieChart },
      { id: 419, title: "Reports", clone: "Creator Hub", path: "/creator/reports", icon: FileBarChart },
      { id: 420, title: "Support", clone: "Creator Hub", path: "/creator/support", icon: LifeBuoy },
      { id: 421, title: "Settings", clone: "Creator Hub", path: "/creator/settings", icon: Settings },
    ],
  },
  {
    label: "Payroll · Pilot",
    items: [
      { id: 500, title: "Payroll Dashboard", clone: "Payroll Pilot", path: "/payroll/dashboard", icon: LayoutDashboard, built: true },
      { id: 501, title: "Employees", clone: "Payroll Pilot", path: "/payroll/employees", icon: Users },
      { id: 502, title: "Attendance", clone: "Payroll Pilot", path: "/payroll/attendance", icon: CalendarCheck },
      { id: 503, title: "Salary Structure", clone: "Payroll Pilot", path: "/payroll/salary", icon: Calculator },
      { id: 504, title: "Bonuses", clone: "Payroll Pilot", path: "/payroll/bonuses", icon: Sparkles },
      { id: 505, title: "Deductions", clone: "Payroll Pilot", path: "/payroll/deductions", icon: TrendingDown },
      { id: 506, title: "Loans", clone: "Payroll Pilot", path: "/payroll/loans", icon: PiggyBank },
      { id: 507, title: "Processing", clone: "Payroll Pilot", path: "/payroll/processing", icon: FlowIcon },
      { id: 508, title: "Disbursements", clone: "Payroll Pilot", path: "/payroll/disbursements", icon: Banknote },
      { id: 509, title: "Payslips", clone: "Payroll Pilot", path: "/payroll/payslips", icon: Pay },
      { id: 510, title: "Tax Compliance", clone: "Payroll Pilot", path: "/payroll/tax", icon: Landmark },
      { id: 511, title: "Reports", clone: "Payroll Pilot", path: "/payroll/reports", icon: FileCheck2 },
      { id: 512, title: "Settings", clone: "Payroll Pilot", path: "/payroll/settings", icon: Settings },
    ],
  },
  {
    label: "MLM · Network",
    items: [
      { id: 600, title: "MLM Dashboard", clone: "MLM Vala", path: "/mlm/dashboard", icon: LayoutDashboard, built: true },
      { id: 601, title: "Members", clone: "MLM Vala", path: "/mlm/members", icon: Users },
      { id: 602, title: "Network Tree", clone: "MLM Vala", path: "/mlm/network", icon: GitFork },
      { id: 603, title: "Packages", clone: "MLM Vala", path: "/mlm/packages", icon: Package },
      { id: 604, title: "Commissions", clone: "MLM Vala", path: "/mlm/commissions", icon: Percent },
      { id: 605, title: "Wallet", clone: "MLM Vala", path: "/mlm/wallet", icon: Wallet },
      { id: 606, title: "Payouts", clone: "MLM Vala", path: "/mlm/payouts", icon: Cash },
      { id: 607, title: "Pools", clone: "MLM Vala", path: "/mlm/pools", icon: Layers },
      { id: 608, title: "Rank Rewards", clone: "MLM Vala", path: "/mlm/ranks", icon: RankIcon },
      { id: 609, title: "Analytics", clone: "MLM Vala", path: "/mlm/analytics", icon: PieChart },
      { id: 610, title: "Reports", clone: "MLM Vala", path: "/mlm/reports", icon: FileBarChart },
      { id: 611, title: "Audit Logs", clone: "MLM Vala", path: "/mlm/audit", icon: ScrollText },
      { id: 612, title: "Integrations", clone: "MLM Vala", path: "/mlm/integrations", icon: Plug },
      { id: 613, title: "White Label", clone: "MLM Vala", path: "/mlm/white-label", icon: Palette },
      { id: 614, title: "Support", clone: "MLM Vala", path: "/mlm/support", icon: LifeBuoy },
      { id: 615, title: "Settings", clone: "MLM Vala", path: "/mlm/settings", icon: Settings },
      { id: 616, title: "SA · Tenants", clone: "MLM Vala", path: "/mlm/sa/tenants", icon: Building2 },
      { id: 617, title: "SA · Plan Engine", clone: "MLM Vala", path: "/mlm/sa/plan-engine", icon: Workflow },
      { id: 618, title: "SA · Revenue", clone: "MLM Vala", path: "/mlm/sa/revenue", icon: TrendingUp },
      { id: 619, title: "SA · Billing", clone: "MLM Vala", path: "/mlm/sa/billing", icon: CreditCard },
      { id: 620, title: "SA · Licenses", clone: "MLM Vala", path: "/mlm/sa/licenses", icon: KeyRound },
      { id: 621, title: "SA · Gateways", clone: "MLM Vala", path: "/mlm/sa/gateways", icon: Plug2 },
      { id: 622, title: "SA · Security", clone: "MLM Vala", path: "/mlm/sa/security", icon: ShieldCheck },
      { id: 623, title: "SA · Cron", clone: "MLM Vala", path: "/mlm/sa/cron", icon: RefreshCw },
      { id: 624, title: "SA · Backup", clone: "MLM Vala", path: "/mlm/sa/backup", icon: Archive },
      { id: 625, title: "SA · System Config", clone: "MLM Vala", path: "/mlm/sa/system", icon: Cpu },
    ],
  },
  {
    label: "POS · Retail OS",
    items: [
      { id: 700, title: "POS Dashboard", clone: "POS Vala", path: "/pos/dashboard", icon: LayoutDashboard, built: true },
      { id: 701, title: "Billing Terminal", clone: "POS Vala", path: "/pos/billing", icon: ScanLine },
      { id: 702, title: "Held Bills", clone: "POS Vala", path: "/pos/held", icon: ClipboardList },
      { id: 703, title: "Payments", clone: "POS Vala", path: "/pos/payments", icon: CreditCard },
      { id: 704, title: "Inventory", clone: "POS Vala", path: "/pos/inventory", icon: Boxes },
      { id: 705, title: "Products & Categories", clone: "POS Vala", path: "/pos/products", icon: Tags },
      { id: 706, title: "Customers", clone: "POS Vala", path: "/pos/customers", icon: UserCircle },
      { id: 707, title: "Shift Manager", clone: "POS Vala", path: "/pos/shift", icon: CalendarCheck },
      { id: 708, title: "Sync Queue", clone: "POS Vala", path: "/pos/sync", icon: RefreshCw },
      { id: 709, title: "Receipts", clone: "POS Vala", path: "/pos/receipts", icon: Receipt },
      { id: 710, title: "Printer", clone: "POS Vala", path: "/pos/printer", icon: Printer },
      { id: 711, title: "Staff", clone: "POS Vala", path: "/pos/staff", icon: Users2 },
      { id: 712, title: "Agents", clone: "POS Vala", path: "/pos/agents", icon: UserCog },
      { id: 713, title: "Agent Banking", clone: "POS Vala", path: "/pos/banking", icon: Landmark },
      { id: 714, title: "Reports", clone: "POS Vala", path: "/pos/reports", icon: FileBarChart },
      { id: 715, title: "Finance", clone: "POS Vala", path: "/pos/finance", icon: BadgeDollarSign },
      { id: 716, title: "Companies", clone: "POS Vala", path: "/pos/companies", icon: Company },
      { id: 717, title: "Franchises", clone: "POS Vala", path: "/pos/franchises", icon: Crown },
      { id: 718, title: "Resellers", clone: "POS Vala", path: "/pos/resellers", icon: Handshake },
      { id: 719, title: "Licenses", clone: "POS Vala", path: "/pos/licenses", icon: KeyRound },
      { id: 720, title: "Branding", clone: "POS Vala", path: "/pos/branding", icon: Palette },
      { id: 721, title: "Feature Control", clone: "POS Vala", path: "/pos/features", icon: Component },
      { id: 722, title: "User Roles", clone: "POS Vala", path: "/pos/roles", icon: Shield },
      { id: 723, title: "API Integrations", clone: "POS Vala", path: "/pos/api", icon: Plug },
      { id: 724, title: "Audit Logs", clone: "POS Vala", path: "/pos/audit", icon: ScrollText },
      { id: 725, title: "Platform Settings", clone: "POS Vala", path: "/pos/settings", icon: Settings },
    ],
  },
  {
    label: "Data · Vault",
    items: [
      { id: 800, title: "Data Vault Dashboard", clone: "Data Vala", path: "/data/dashboard", icon: LayoutDashboard, built: true },
      { id: 801, title: "Marketplace", clone: "Data Vala", path: "/data/marketplace", icon: Store },
      { id: 802, title: "Browse Datasets", clone: "Data Vala", path: "/data/browse", icon: Search },
      { id: 803, title: "Categories", clone: "Data Vala", path: "/data/categories", icon: Layers },
      { id: 804, title: "Compare", clone: "Data Vala", path: "/data/compare", icon: BarChart2 },
      { id: 805, title: "Data Viewer", clone: "Data Vala", path: "/data/viewer", icon: Eye },
      { id: 806, title: "Extractors", clone: "Data Vala", path: "/data/extractors", icon: Filter },
      { id: 807, title: "AI Extractor", clone: "Data Vala", path: "/data/ai-extractor", icon: Sparkle },
      { id: 808, title: "One-Click Extractor", clone: "Data Vala", path: "/data/one-click", icon: Zap },
      { id: 809, title: "AI API", clone: "Data Vala", path: "/data/ai-api", icon: BrainCircuit },
      { id: 810, title: "Favorites", clone: "Data Vala", path: "/data/favorites", icon: Heart },
      { id: 811, title: "My Purchases", clone: "Data Vala", path: "/data/purchases", icon: ShoppingBag },
      { id: 812, title: "Purchase Wizard", clone: "Data Vala", path: "/data/wizard", icon: Wand2 },
      { id: 813, title: "Wallet", clone: "Data Vala", path: "/data/wallet", icon: Wallet },
      { id: 814, title: "Billing", clone: "Data Vala", path: "/data/billing", icon: CreditCard },
      { id: 815, title: "Pricing", clone: "Data Vala", path: "/data/pricing", icon: BadgeDollarSign },
      { id: 816, title: "Activity", clone: "Data Vala", path: "/data/activity", icon: Activity },
      { id: 817, title: "Activity Analytics", clone: "Data Vala", path: "/data/activity-analytics", icon: PieChart },
      { id: 818, title: "Comparison Analytics", clone: "Data Vala", path: "/data/comparison", icon: ChartBar },
      { id: 819, title: "Client Console", clone: "Data Vala", path: "/data/client-portal", icon: UserCircle },
      { id: 820, title: "Reseller Console", clone: "Data Vala", path: "/data/reseller", icon: Handshake },
      { id: 821, title: "Mobile App", clone: "Data Vala", path: "/data/mobile", icon: Smartphone },
      { id: 822, title: "Component Showcase", clone: "Data Vala", path: "/data/showcase", icon: Component },
      { id: 823, title: "Profile", clone: "Data Vala", path: "/data/profile", icon: UserCircle },
      { id: 824, title: "Settings", clone: "Data Vala", path: "/data/settings", icon: Settings },
      { id: 825, title: "Super Admin", clone: "Data Vala", path: "/data/super-admin", icon: ShieldAlert },
    ],
  },
  {
    label: "Dezortn · Growth OS",
    items: [
      { id: 900, title: "Growth Dashboard", clone: "Dezortn", path: "/growth/dashboard", icon: LayoutDashboard, built: true },
      { id: 901, title: "Companies", clone: "Dezortn", path: "/growth/companies", icon: Company },
      { id: 902, title: "Company Detail", clone: "Dezortn", path: "/growth/company-detail", icon: Building },
      { id: 903, title: "Leads", clone: "Dezortn", path: "/growth/leads", icon: UserPlus2 },
      { id: 904, title: "Lead Detail", clone: "Dezortn", path: "/growth/lead-detail", icon: UserCircle },
      { id: 905, title: "Employees", clone: "Dezortn", path: "/growth/employees", icon: Users2 },
      { id: 906, title: "Employee Profile", clone: "Dezortn", path: "/growth/employee-profile", icon: UserCircle },
      { id: 907, title: "Resellers", clone: "Dezortn", path: "/growth/resellers", icon: Handshake },
      { id: 908, title: "Reseller Console", clone: "Dezortn", path: "/growth/reseller-console", icon: UserCog },
      { id: 909, title: "Reseller Profile", clone: "Dezortn", path: "/growth/reseller-profile", icon: UserCircle },
      { id: 910, title: "Campaigns", clone: "Dezortn", path: "/growth/campaigns", icon: Megaphone },
      { id: 911, title: "Campaign Analytics", clone: "Dezortn", path: "/growth/campaign-analytics", icon: PieChart },
      { id: 912, title: "Ratings", clone: "Dezortn", path: "/growth/ratings", icon: Star },
      { id: 913, title: "SEO", clone: "Dezortn", path: "/growth/seo", icon: SearchCheck },
      { id: 914, title: "Grow Business", clone: "Dezortn", path: "/growth/grow", icon: Growth },
      { id: 915, title: "Product Detail", clone: "Dezortn", path: "/growth/product", icon: Package },
      { id: 916, title: "Wallet", clone: "Dezortn", path: "/growth/wallet", icon: Wallet },
      { id: 917, title: "Payments", clone: "Dezortn", path: "/growth/payments", icon: CreditCard },
      { id: 918, title: "Payment History", clone: "Dezortn", path: "/growth/payment-history", icon: ScrollText },
      { id: 919, title: "Cashier", clone: "Dezortn", path: "/growth/cashier", icon: ScanLine },
      { id: 920, title: "Reports", clone: "Dezortn", path: "/growth/reports", icon: FileBarChart },
      { id: 921, title: "Admin Panel", clone: "Dezortn", path: "/growth/admin", icon: ShieldAlert },
      { id: 922, title: "Portal", clone: "Dezortn", path: "/growth/portal", icon: Globe },
      { id: 923, title: "Settings", clone: "Dezortn", path: "/growth/settings", icon: Settings },
    ],
  },
  {
    label: "Vala · Nexus Command",
    items: [
      { id: 1000, title: "Vala Command", clone: "Vala Nexus", path: "/vala/dashboard", icon: LayoutDashboard, built: true },
      { id: 1001, title: "Control Spine", clone: "Vala Nexus", path: "/vala/control", icon: Component },
      { id: 1002, title: "Super Admin", clone: "Vala Nexus", path: "/vala/super-admin", icon: Crown },
      { id: 1003, title: "Master Admin", clone: "Vala Nexus", path: "/vala/master-admin", icon: ShieldAlert },
      { id: 1004, title: "Master Control", clone: "Vala Nexus", path: "/vala/master-control", icon: Cpu },
      { id: 1005, title: "Continent Console", clone: "Vala Nexus", path: "/vala/continent-super", icon: Globe2 },
      { id: 1006, title: "Enterprise OS", clone: "Vala Nexus", path: "/vala/enterprise", icon: Building2 },
      { id: 1007, title: "Enterprise Control", clone: "Vala Nexus", path: "/vala/enterprise-control", icon: Network },
      { id: 1008, title: "Leader Security", clone: "Vala Nexus", path: "/vala/leader-security", icon: ShieldCheck },
      { id: 1009, title: "Security Command", clone: "Vala Nexus", path: "/vala/security-command", icon: Shield },
      { id: 1010, title: "Secure System", clone: "Vala Nexus", path: "/vala/secure-system", icon: Lock },
      { id: 1011, title: "Incident & Crisis", clone: "Vala Nexus", path: "/vala/incident", icon: Radar },
      { id: 1012, title: "Server Grid", clone: "Vala Nexus", path: "/vala/server", icon: Server },
      { id: 1013, title: "Server Manager", clone: "Vala Nexus", path: "/vala/server-manager", icon: HardDrive },
      { id: 1014, title: "API Manager", clone: "Vala Nexus", path: "/vala/api-manager", icon: Plug },
      { id: 1015, title: "API · AI Bridge", clone: "Vala Nexus", path: "/vala/api-ai", icon: BrainCircuit },
      { id: 1016, title: "AI Console", clone: "Vala Nexus", path: "/vala/ai-console", icon: Bot },
      { id: 1017, title: "Dev Command Center", clone: "Vala Nexus", path: "/vala/dev-command", icon: Terminal },
      { id: 1018, title: "Developer Hub", clone: "Vala Nexus", path: "/vala/developer", icon: Code2 },
      { id: 1019, title: "Dev Manager", clone: "Vala Nexus", path: "/vala/dev-manager", icon: GitBranch },
      { id: 1020, title: "HR Manager", clone: "Vala Nexus", path: "/vala/hr", icon: Users2 },
      { id: 1021, title: "Finance Manager", clone: "Vala Nexus", path: "/vala/finance", icon: Banknote },
      { id: 1022, title: "Marketing Manager", clone: "Vala Nexus", path: "/vala/marketing", icon: Megaphone },
      { id: 1023, title: "Sales Support", clone: "Vala Nexus", path: "/vala/sales-support", icon: Headset },
      { id: 1024, title: "Lead Manager", clone: "Vala Nexus", path: "/vala/lead", icon: Target },
      { id: 1025, title: "Performance Manager", clone: "Vala Nexus", path: "/vala/performance", icon: Gauge },
      { id: 1026, title: "Legal Compliance", clone: "Vala Nexus", path: "/vala/legal", icon: Scale },
      { id: 1027, title: "SEO Manager", clone: "Vala Nexus", path: "/vala/seo", icon: SearchCheck },
      { id: 1028, title: "Task Manager", clone: "Vala Nexus", path: "/vala/task", icon: KanbanSquare },
      { id: 1029, title: "Billing", clone: "Vala Nexus", path: "/vala/billing", icon: CreditCard },
      { id: 1030, title: "Franchise Suite", clone: "Vala Nexus", path: "/vala/franchise", icon: Building },
      { id: 1031, title: "Franchise Manager", clone: "Vala Nexus", path: "/vala/franchise-manager", icon: UserCog },
      { id: 1032, title: "Reseller Hub", clone: "Vala Nexus", path: "/vala/reseller", icon: Handshake },
      { id: 1033, title: "Reseller Portal", clone: "Vala Nexus", path: "/vala/reseller-portal", icon: Globe },
      { id: 1034, title: "Influencer Command", clone: "Vala Nexus", path: "/vala/influencer", icon: Star },
      { id: 1035, title: "Influencer Manager", clone: "Vala Nexus", path: "/vala/influencer-manager", icon: Megaphone },
      { id: 1036, title: "Client Success", clone: "Vala Nexus", path: "/vala/client-success", icon: HeartPulse },
      { id: 1037, title: "Client Portal", clone: "Vala Nexus", path: "/vala/client-portal", icon: UserCircle },
      { id: 1038, title: "Prime User Suite", clone: "Vala Nexus", path: "/vala/prime-user", icon: Crown },
      { id: 1039, title: "Career Portal", clone: "Vala Nexus", path: "/vala/career-portal", icon: Briefcase },
      { id: 1040, title: "Apply Portal", clone: "Vala Nexus", path: "/vala/apply-portal", icon: ClipboardList },
      { id: 1041, title: "Sectors Browse", clone: "Vala Nexus", path: "/vala/sectors", icon: Layers3 },
      { id: 1042, title: "Category Onboarding", clone: "Vala Nexus", path: "/vala/category-onboard", icon: Boxes },
      { id: 1043, title: "Sub-Category Demos", clone: "Vala Nexus", path: "/vala/sub-demos", icon: PlayCircle },
      { id: 1044, title: "Demo Directory", clone: "Vala Nexus", path: "/vala/demo-directory", icon: ListTree },
      { id: 1045, title: "Demo Showcase", clone: "Vala Nexus", path: "/vala/demo-showcase", icon: PlaySquare },
      { id: 1046, title: "Premium Demo", clone: "Vala Nexus", path: "/vala/premium-demo", icon: Sparkles },
      { id: 1047, title: "Product Demo Mgr", clone: "Vala Nexus", path: "/vala/product-demo", icon: Presentation },
      { id: 1048, title: "Demo Manager", clone: "Vala Nexus", path: "/vala/demo-manager", icon: Tv2 },
      { id: 1049, title: "Demo Access", clone: "Vala Nexus", path: "/vala/demo-access", icon: KeyRound },
      { id: 1050, title: "Demo Login", clone: "Vala Nexus", path: "/vala/demo-login", icon: Lock },
      { id: 1051, title: "Demo Credentials", clone: "Vala Nexus", path: "/vala/demo-credentials", icon: FileBadge },
      { id: 1052, title: "Simple Demo View", clone: "Vala Nexus", path: "/vala/simple-demo", icon: Eye },
      { id: 1053, title: "API Integration", clone: "Vala Nexus", path: "/vala/api-integration", icon: Plug2 },
      { id: 1054, title: "Buzzer Console", clone: "Vala Nexus", path: "/vala/notification-buzzer", icon: Bell },
      { id: 1055, title: "Internal Chat", clone: "Vala Nexus", path: "/vala/internal-chat", icon: MessagesSquare },
      { id: 1056, title: "Personal Chat", clone: "Vala Nexus", path: "/vala/personal-chat", icon: MessageSquare },
      { id: 1057, title: "Promise Tracker", clone: "Vala Nexus", path: "/vala/promise-tracker", icon: BadgeCheck },
      { id: 1058, title: "Promise Management", clone: "Vala Nexus", path: "/vala/promise-mgmt", icon: ClipboardCheck },
      { id: 1059, title: "R&D Lab", clone: "Vala Nexus", path: "/vala/rnd", icon: BrainCircuit },
      { id: 1060, title: "Pro Manager", clone: "Vala Nexus", path: "/vala/pro-manager", icon: Award },
      { id: 1061, title: "Assist Manager", clone: "Vala Nexus", path: "/vala/assist-manager", icon: LifeBuoy },
      { id: 1062, title: "Safe Assist", clone: "Vala Nexus", path: "/vala/safe-assist", icon: Shield },
      { id: 1063, title: "System Settings", clone: "Vala Nexus", path: "/vala/system-settings", icon: Settings },
      { id: 1064, title: "Public Homepage", clone: "Vala Nexus", path: "/vala/homepage", icon: Globe },
      { id: 1065, title: "Landing", clone: "Vala Nexus", path: "/vala/landing", icon: Rocket },
    ],
  },
];

export const ALL_ITEMS: NavItem[] = NAV_GROUPS.flatMap((g) => g.items);
